# -*- coding: utf-8 -*-
"""Sprint3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11E5Cyg4CTIxBjRoesRcbEWbkUamdB89U

# **Análise exploratória com Python**

# **Analisando índices e ações**

*O objetivo dessa análise é mostrar que investimento certo não existe, existe apenas oportunidade e oportunismo no mercado financeiro*
"""

!pip install yfinance
!pip install yahoofinancials

import pandas as pd
import yfinance as yf
from yahoofinancials import YahooFinancials

yahoo_financials = YahooFinancials('NQ=F')
data = yahoo_financials.get_historical_price_data(
    start_date='2020-03-01', end_date='2023-01-01', time_interval='weekly')

"""***O índice utilizado aqui é o Nasdaq 100, O Nasdaq 100 é um índice composto pelas 100 maiores empresas não financeiras negociadas na bolsa de valores Nasdaq. As empresas listadas na Nasdaq com maior representação são as chamadas big techs, empresas com foco no desenvolvimento tecnológico que abocanham grande parte de seus respectivos mercados.***"""

NQ_F = pd.DataFrame(data['NQ=F']['prices'])
NQ_F = NQ_F.drop('date', axis=1).set_index('formatted_date')

NQ_F.head(148)

NQ_F.info()

import matplotlib.pyplot as plt  
import seaborn as sns

"""*Logo abaixo temos um gráfico de dispersão que utiliza a data como eixo **X** e a alta da semana como eixo **Y**.*"""

sns.relplot(data=NQ_F, x='formatted_date', y="high")

"""*Agora vamos analisar o gráfico de linha abaixo que segue as regras de eixo X e Y do gráfico acima:
Podemos tirar algumas conclusões apenas olhando este gráfico.
A primeira, temos um crescimento no valor de mercado assombroso a partir de março de 2020 até novembro de 2021.
a segunda é que, a partir do final de 2021 até o começo de 2023 temos oscilações em quedas significativas(aproximadamente 1/3 do valor).*
"""

plt.figure(figsize=(50,48))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=NQ_F, x='formatted_date', y='high', color='blue')

"""***Com esses dois pontos podemos sugerir mais uma coisa, o período da pandemia supervalorizou o valor das empresas de tecnologia, streamings, serviços de entrega por delivery e transporte pelo fato de terem ocorridos diversos lockdowns e a implementação de trabalho remoto em todo mundo. Mas com o fim da pandemia da Covid-19 o mercado despencou.***

Para dar mais força ao argumento apresentado vamos analisar ações de empresas levando em conta o mesmo período como exemplo:
"""

yahoo_financials = YahooFinancials('AMZN')
data = yahoo_financials.get_historical_price_data(
    start_date='2020-03-01', end_date='2023-01-01', time_interval='weekly')

AMZN = pd.DataFrame(data['AMZN']['prices'])
AMZN = AMZN.drop('date', axis=1).set_index('formatted_date')

"""***Vamos analisar o histórico de ações da Amazon, uma das maiores bigtechs no mundo.***"""

AMZN.head(148)

AMZN.info()

sns.relplot(data=AMZN, x='formatted_date', y="high", color='red')

plt.figure(figsize=(50,48))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=AMZN, x='formatted_date', y='high', color='red')

"""*Aqui vai mais um ponto para nossa argumentação:
Observando os gráficos acima vemos o mesmo comportamento apresentado quando vimos o hitórico da NASDAQ.*
"""

yahoo_financials = YahooFinancials('UBER')
data = yahoo_financials.get_historical_price_data(
    start_date='2020-03-01', end_date='2023-01-01', time_interval='weekly')

UBER = pd.DataFrame(data['UBER']['prices'])
UBER = UBER.drop('date', axis=1).set_index('formatted_date')

"""***Vamos olhar agora o histórico da Uber, empresa de serviço de transporte.***"""

UBER.head(148)

UBER.info()

sns.relplot(data=UBER, x='formatted_date', y="high", color='green')

plt.figure(figsize=(50,48))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=UBER, x='formatted_date', y='high', color='green')

"""*Com uma rápida vizualização e comparação vemos o mesmo comportamento dos históricos das empresas/índices anteriores.*

***Vamos ver o histórico da Netflix, um dos maiores streamings do mundo.***
"""

yahoo_financials = YahooFinancials('NFLX')
data = yahoo_financials.get_historical_price_data(
    start_date='2020-03-01', end_date='2023-01-01', time_interval='weekly')

NFLX = pd.DataFrame(data['NFLX']['prices'])
NFLX = NFLX.drop('date', axis=1).set_index('formatted_date')

NFLX.head(148)

NFLX.info()

sns.relplot(data=NFLX, x='formatted_date', y="high", color='black')

plt.figure(figsize=(50,48))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=NFLX, x='formatted_date', y='high', color='black')

"""*Mais um caso que reforça nosso argumento.*

***Agora vamos olhar o histórico de ações da Meta que dispensa apresentações.***
"""

yahoo_financials = YahooFinancials('META')
data = yahoo_financials.get_historical_price_data(
    start_date='2020-03-01', end_date='2023-01-01', time_interval='weekly')

META = pd.DataFrame(data['META']['prices'])
META = META.drop('date', axis=1).set_index('formatted_date')

META.head(148)

META.info()

sns.relplot(data=META, x='formatted_date', y="high", color='purple')

plt.figure(figsize=(50,48))
plt.xticks(rotation=45)
sns.set_theme(style="darkgrid")
sns.lineplot(data=META, x='formatted_date', y='high', color='purple')

"""Analisando 1 índice que contempla as 100 maiores empresas não financeiras do mundo e 4 empresas gigantes detalhadamente, comparando uma a uma, podemos ter certeza que não foi um comportamento isolado mas sim geral.

# **Tirando médias**

***Agora, iremos ver qual foi o tamanho do prejuízo das empresas aqui analisadas em porcentagem, para termos uma média de crescimento e queda no decorrer do período analisado. Levando em consideração o início das datas, o pico de valor das cotações e o valor no fim do período***
"""

Cotacoes_Selecionadas =  [['Amazon', 99, 185, 85],
            ['Uber', 35, 60, 25],
            ['Netflix', 393, 690, 295],
            ['Meta', 197, 378, 121]]

CS = pd.DataFrame(Cotacoes_Selecionadas, columns=['Empresa', 'Início', 'Pico de valor', 'Final'])

CS.head()

New_CS = [['Amazon', 186, 45],
          ['Uber', 171, 41],
          ['Netflix', 175, 42],
          ['Meta', 191, 32]]

NCS = pd.DataFrame(New_CS, columns=['Empresa', 'Aumento em %', 'Queda em %'])

NCS.head()

import statistics

print("A média de aumento em % é de: ", statistics.fmean(NCS['Aumento em %']))

"""***Acima utilizando a biblioteca statistics tiramos a média de aumento dos valores das ações das empresas no início do período até o pico de preço das ações. Vemos que é um número exorbitante***"""

print("A média de queda em % é de: ", statistics.fmean(NCS['Queda em %']))

"""***Após o período de pandemia vemos uma queda gigantesca como média nas empresas analisadas.***

# **Conclusão**

Com os dados e gráficos apresentados podemos tirar várias conclusões. Mas nosso intuíto aqui é mostrar o quanto o mercado é mais oportunidade e oportunismo do que uma fórmula mágica para ganhar dinheiro. Na maior crise do nosso século, tivemos um "boom" nas ações de diversas empresas, e quem tinha como e conseguiu aproveitar para comprar antes de subir e vendeu antes de começar a despencar realmente ganhou muito dinheiro. Isso passa longe de significar que investir nas empresas de tecnologia é tiro certo, muito pelo contrário, mostramos que recentemente as empresas tomaram mais prejuízos do que lucros.
E só é possível se previnir quando se conhece o terreno, aqui a análise foi feita para mostrar que é um risco investir, mas pode-se aprender sobre e se previnir para fazer as decisões certas.
Nosso projeto é educativo, e tem o intuíto de ensinar quem quer aprender sobre esse assunto.
"""